baseURL = "https://upbeat-franklin-561986.netlify.app"
title = "Learn 2 Swap - ParaSwap Community Handbook"
siteDescription = "Community Documentation for ParaSwap - the Decentralised Finance middelware facilitating token swaps."
enableRobotsTXT = true
theme = ["hugo-notice","compose"]
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Handbook"
    weight = 2
    url = "/docs/"

[[menu.main]]
    name = "ParaSwap"
    weight = 3
    url = "https://paraswap.io/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

# Everything below this are Site Params

[params]
  author = "ParaSwap"
  searchPlaceholder = "Search the docs ..."
  repo = "https://github.com/onweru/compose"

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  [params.logo]
    lightMode = "logo/logo_paraswap-handbook-blue.svg"
    darkMode = "logo/logo_paraswap-handbook.svg"
